1) ** pdf con tabla de datos **

In [ ]:
#descargamos el pdf
!wget https://www.indec.gob.ar/uploads/informesdeprensa/ipc_01_23891D383E4F.pdf

--2023-04-02 11:24:02--  https://www.indec.gob.ar/uploads/informesdeprensa/ipc_01_23891D383E4F.pdf
Resolving www.indec.gob.ar (www.indec.gob.ar)... 186.33.230.196
Connecting to www.indec.gob.ar (www.indec.gob.ar)|186.33.230.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1021492 (998K) [application/pdf]
Saving to: ‘ipc_01_23891D383E4F.pdf’

ipc_01_23891D383E4F 100%[===================>] 997.55K  1.31MB/s    in 0.7s

2023-04-02 11:24:04 (1.31 MB/s) - ‘ipc_01_23891D383E4F.pdf’ saved [1021492/1021492]

In [ ]:
#instalamos el módulo
!pip install "camelot-py[cv]"

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting camelot-py[cv]
  Downloading camelot_py-0.11.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 KB 1.5 MB/s eta 0:00:00
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (3.0.10)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (1.4.4)
Collecting pypdf>=3.0.0
  Downloading pypdf-3.7.0-py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.9/246.9 KB 5.6 MB/s eta 0:00:00
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (8.1.3)
Collecting pdfminer.six>=20200726
  Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 45.3 MB/s eta 0:00:00
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (4.0.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (1.22.4)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (0.8.10)
Collecting pdftopng>=0.2.3
  Downloading pdftopng-0.2.3-cp39-cp39-manylinux2010_x86_64.whl (11.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 34.6 MB/s eta 0:00:00
Collecting ghostscript>=0.7
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.9/dist-packages (from camelot-py[cv]) (4.7.0.72)
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.9/dist-packages (from ghostscript>=0.7->camelot-py[cv]) (67.6.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.4->camelot-py[cv]) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.4->camelot-py[cv]) (2.8.2)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (2.0.12)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.9/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (40.0.1)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.9/dist-packages (from pypdf>=3.0.0->camelot-py[cv]) (4.5.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (1.15.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas>=0.23.4->camelot-py[cv]) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (2.21)
Installing collected packages: pypdf, pdftopng, ghostscript, pdfminer.six, camelot-py
Successfully installed camelot-py-0.11.0 ghostscript-0.7 pdfminer.six-20221105 pdftopng-0.2.3 pypdf-3.7.0

In [ ]:
#cargamos la librería camelot
import camelot

In [ ]:
#se crea una tabla con la tabla de datos extraída del pdf
tables = camelot.read_pdf('/content/ipc_01_23891D383E4F.pdf', pages="12", flavor="stream", suppress_stdout=True)

In [ ]:
#se observa la tabla extraída
df1=tables[0].df
df1

,0,1,2,3,4,5,6
0,Principales aperturas,,,,,,
1,,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
2,,,,,Porcentaje,,
3,Nivel general,"5,3","5,1","4,8","4,7","5,0","4,5"
4,Alimentos y bebidas no alcohólicas,"5,5","4,5","3,6","3,3","2,7","3,4"
5,Alimentos,"5,2","4,4","3,5","3,1","2,4","3,2"
6,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
7,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
8,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
9,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
10,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
11,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
12,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
13,Bebidas no alcohólicas,"7,6","5,6","4,1","5,0","6,3","5,3"
14,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
15,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
16,Bebidas alcohólicas y tabaco,"6,7","7,5","7,0","7,4","8,2","7,1"
17,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
18,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
19,Prendas de vestir y calzado,"4,1","3,8","4,5","4,2","4,3","4,2"
20,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
21,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
22,"Vivienda, agua, electricidad, gas y otros comb...","4,2","4,4","4,4","3,5","3,6","4,3"
23,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
24,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
25,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
26,Equipamiento y mantenimiento del hogar,"6,3","5,5","6,6","6,4","6,0","4,0"
27,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
28,Salud,"5,5","6,0","5,2","5,5","5,6","5,7"
29,"Productos medicinales, artefactos y equipos pa...",,,,,,
30,,"5,4","5,6","5,2","6,1","5,4","6,0"
31,salud,,,,,,
32,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
33,Transporte,"5,1","6,1","6,3","6,2","8,1","5,1"
34,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
35,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
36,Combustibles y lubricantes para vehículos de uso,,,,,,
37,,"4,2","7,2","7,5","7,2","8,0","5,9"
38,del hogar,,,,,,
39,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
40,Comunicación,"2,6","3,5","3,7","5,5","6,2","3,6"
41,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
42,Recreación y cultura,"3,9","4,7","6,5","6,4","4,9","6,0"
43,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
44,"Periódicos, diarios, revistas, libros y artícu...",,,,,,
45,,"5,0","4,7","4,5","4,9","5,5","3,8"
46,papelería,,,,,,
47,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
48,Restaurantes y hoteles,"7,4","6,7","7,4","6,5","8,5","7,4"
49,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
50,Bienes y servicios varios,"6,0","5,5","4,5","6,6","5,7","5,1"
51,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#se borran las filas 0 y 2 y las que tienen valores generales (que no utilizaremos)
df2=df1.drop([0,2,3,4,5,13,16,19,22,26,28,33,40,42,48,50], axis=0)
df2.reset_index(drop=True, inplace=True)
df2

,0,1,2,3,4,5,6
0,,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
1,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
2,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
3,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
4,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
5,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
6,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
7,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
8,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
9,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
10,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
11,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
12,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
13,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
14,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
15,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
16,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
17,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
18,"Productos medicinales, artefactos y equipos pa...",,,,,,
19,,"5,4","5,6","5,2","6,1","5,4","6,0"
20,salud,,,,,,
21,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
22,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
23,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
24,Combustibles y lubricantes para vehículos de uso,,,,,,
25,,"4,2","7,2","7,5","7,2","8,0","5,9"
26,del hogar,,,,,,
27,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
28,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
29,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
30,"Periódicos, diarios, revistas, libros y artícu...",,,,,,
31,,"5,0","4,7","4,5","4,9","5,5","3,8"
32,papelería,,,,,,
33,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
34,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
35,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#reemplazar nombres de columnas por la primer fila

df2=df2.rename(columns=df2.iloc[0]).drop(df2.index[0])
df2.reset_index(drop=True, inplace=True)
df2

,,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
1,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
2,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
3,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
4,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
5,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
6,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
7,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
8,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
9,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
10,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
11,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
12,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
13,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
14,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
15,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
16,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
17,"Productos medicinales, artefactos y equipos pa...",,,,,,
18,,"5,4","5,6","5,2","6,1","5,4","6,0"
19,salud,,,,,,
20,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
21,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
22,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
23,Combustibles y lubricantes para vehículos de uso,,,,,,
24,,"4,2","7,2","7,5","7,2","8,0","5,9"
25,del hogar,,,,,,
26,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
27,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
28,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
29,"Periódicos, diarios, revistas, libros y artícu...",,,,,,
30,,"5,0","4,7","4,5","4,9","5,5","3,8"
31,papelería,,,,,,
32,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
33,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
34,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#renombro la primer columna
df3=df2.rename(columns={'': 'Producto'})
df3

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
1,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
2,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
3,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
4,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
5,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
6,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
7,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
8,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
9,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
10,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
11,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
12,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
13,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
14,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
15,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
16,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
17,"Productos medicinales, artefactos y equipos pa...",,,,,,
18,,"5,4","5,6","5,2","6,1","5,4","6,0"
19,salud,,,,,,
20,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
21,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
22,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
23,Combustibles y lubricantes para vehículos de uso,,,,,,
24,,"4,2","7,2","7,5","7,2","8,0","5,9"
25,del hogar,,,,,,
26,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
27,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
28,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
29,"Periódicos, diarios, revistas, libros y artícu...",,,,,,
30,,"5,0","4,7","4,5","4,9","5,5","3,8"
31,papelería,,,,,,
32,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
33,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
34,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#se verifica individualmente, por ejemplo
df3.iloc[17,0]

'Productos medicinales, artefactos y equipos para la'

In [ ]:
#se coluca el nombre del producto en las columnas que tienen numeros y estan vacias
df3.iloc[18,0] = df3.iloc[17,0] + ' ' + df3.iloc[19,0]
df3.iloc[24,0] = df3.iloc[23,0] + ' ' + df3.iloc[25,0]
df3.iloc[30,0] = df3.iloc[29,0] + ' ' + df3.iloc[31,0]
df3

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
1,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
2,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
3,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
4,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
5,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
6,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
7,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
8,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
9,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
10,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
11,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
12,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
13,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
14,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
15,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
16,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
17,"Productos medicinales, artefactos y equipos pa...",,,,,,
18,"Productos medicinales, artefactos y equipos pa...","5,4","5,6","5,2","6,1","5,4","6,0"
19,salud,,,,,,
20,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
21,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
22,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
23,Combustibles y lubricantes para vehículos de uso,,,,,,
24,Combustibles y lubricantes para vehículos de u...,"4,2","7,2","7,5","7,2","8,0","5,9"
25,del hogar,,,,,,
26,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
27,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
28,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
29,"Periódicos, diarios, revistas, libros y artícu...",,,,,,
30,"Periódicos, diarios, revistas, libros y artícu...","5,0","4,7","4,5","4,9","5,5","3,8"
31,papelería,,,,,,
32,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
33,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
34,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#se borran las filas que no contienen datos
df4=df3.drop([17,19,23,25,29,31], axis=0)
df4.reset_index(drop=True, inplace=True)
df4

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,"6,7","5,5","4,7","3,9","5,6","4,6"
1,Carnes y derivados,"3,0","2,8","3,0","1,9","1,3","1,5"
2,"Leche, productos lácteos y huevos","4,4","5,2","3,3","3,7","5,5","4,7"
3,"Aceites, grasas y manteca","3,3","3,4","2,3","2,5","3,0","3,8"
4,Frutas,"10,0","11,8","9,5","10,1","11,9","10,8"
5,"Verduras, tubérculos y legumbres","8,9","3,7","1,9","1,8","-7,1","-0,8"
6,"Azúcar, dulces, chocolate, golosinas, etc.","4,0","4,3","2,9","4,2","4,3","4,0"
7,"Café, té, yerba y cacao","3,4","3,3","2,5","3,9","5,8","3,1"
8,"Aguas minerales, bebidas gaseosas y jugos","9,3","6,8","4,9","5,3","6,5","6,2"
9,Bebidas alcohólicas,"7,1","8,4","7,3","8,4","10,0","7,8"
10,Tabaco,"6,4","6,5","6,4","6,5","6,8","6,4"
11,Prendas de vestir y materiales,"3,7","3,4","4,5","4,3","5,0","4,4"
12,Calzado,"5,2","5,1","4,5","4,2","2,6","3,8"
13,Alquiler de la vivienda y gastos conexos,"4,9","5,2","1,7","2,6","2,4","0,3"
14,Alquiler de la vivienda,"4,7","5,2","1,4","2,3","2,3","0,1"
15,"Electricidad, gas y otros combustibles","2,1","3,9","4,1","3,3","4,7","8,1"
16,Bienes y servicios para la conservación del hogar,"5,8","5,8","6,2","6,8","6,1","5,3"
17,"Productos medicinales, artefactos y equipos pa...","5,4","5,6","5,2","6,1","5,4","6,0"
18,Gastos de prepagas,"6,9","8,6","8,3","4,5","6,8","7,0"
19,Adquisición de vehículos,"6,2","4,2","4,9","5,4","4,3","3,7"
20,Funcionamiento de equipos de transporte personal,"3,9","7,1","7,0","6,9","8,1","6,8"
21,Combustibles y lubricantes para vehículos de u...,"4,2","7,2","7,5","7,2","8,0","5,9"
22,Transporte público,"5,7","8,5","7,9","5,6","18,6","5,8"
23,Servicios de telefonía e internet,"2,7","3,5","3,5","5,9","6,2","3,6"
24,Servicios recreativos y culturales,"6,2","8,0","13,5","5,3","3,0","7,9"
25,"Periódicos, diarios, revistas, libros y artícu...","5,0","4,7","4,5","4,9","5,5","3,8"
26,Educación,"5,5","2,9","1,1","0,8","2,1","1,7"
27,Restaurantes y comidas fuera del hogar,"7,4","6,6","7,4","6,4","8,5","7,3"
28,Cuidado personal,"5,9","5,4","4,5","6,9","5,7","5,1"

In [ ]:
#se verifica si hay datos faltantes
df4.isna().sum()

Producto     0
GBA          0
Pampeana     0
Noreste      0
Noroeste     0
Cuyo         0
Patagonia    0
dtype: int64

In [ ]:
#se verifican los tipos de datos
df4.dtypes

Producto     object
GBA          object
Pampeana     object
Noreste      object
Noroeste     object
Cuyo         object
Patagonia    object
dtype: object

In [ ]:
import pandas as pd

Vamos a convertir los datos de tipo objeto a numericos

In [ ]:
# Reemplazamos comas por puntos en todas las columnas
df4 = df4.replace(',', '.', regex=True)

In [ ]:
# Convertimos las columnas de tipo object a tipo float excepto la columna Producto que no es numerica
for col in df4.columns:
    if df4[col].dtype == 'object' and col != 'Producto':
        df4[col] = pd.to_numeric(df4[col], errors='coerce')

In [ ]:
df4.dtypes

Producto      object
GBA          float64
Pampeana     float64
Noreste      float64
Noroeste     float64
Cuyo         float64
Patagonia    float64
dtype: object

In [ ]:
df4

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,6.7,5.5,4.7,3.9,5.6,4.6
1,Carnes y derivados,3.0,2.8,3.0,1.9,1.3,1.5
2,Leche. productos lácteos y huevos,4.4,5.2,3.3,3.7,5.5,4.7
3,Aceites. grasas y manteca,3.3,3.4,2.3,2.5,3.0,3.8
4,Frutas,10.0,11.8,9.5,10.1,11.9,10.8
5,Verduras. tubérculos y legumbres,8.9,3.7,1.9,1.8,-7.1,-0.8
6,Azúcar. dulces. chocolate. golosinas. etc.,4.0,4.3,2.9,4.2,4.3,4.0
7,Café. té. yerba y cacao,3.4,3.3,2.5,3.9,5.8,3.1
8,Aguas minerales. bebidas gaseosas y jugos,9.3,6.8,4.9,5.3,6.5,6.2
9,Bebidas alcohólicas,7.1,8.4,7.3,8.4,10.0,7.8
10,Tabaco,6.4,6.5,6.4,6.5,6.8,6.4
11,Prendas de vestir y materiales,3.7,3.4,4.5,4.3,5.0,4.4
12,Calzado,5.2,5.1,4.5,4.2,2.6,3.8
13,Alquiler de la vivienda y gastos conexos,4.9,5.2,1.7,2.6,2.4,0.3
14,Alquiler de la vivienda,4.7,5.2,1.4,2.3,2.3,0.1
15,Electricidad. gas y otros combustibles,2.1,3.9,4.1,3.3,4.7,8.1
16,Bienes y servicios para la conservación del hogar,5.8,5.8,6.2,6.8,6.1,5.3
17,Productos medicinales. artefactos y equipos pa...,5.4,5.6,5.2,6.1,5.4,6.0
18,Gastos de prepagas,6.9,8.6,8.3,4.5,6.8,7.0
19,Adquisición de vehículos,6.2,4.2,4.9,5.4,4.3,3.7
20,Funcionamiento de equipos de transporte personal,3.9,7.1,7.0,6.9,8.1,6.8
21,Combustibles y lubricantes para vehículos de u...,4.2,7.2,7.5,7.2,8.0,5.9
22,Transporte público,5.7,8.5,7.9,5.6,18.6,5.8
23,Servicios de telefonía e internet,2.7,3.5,3.5,5.9,6.2,3.6
24,Servicios recreativos y culturales,6.2,8.0,13.5,5.3,3.0,7.9
25,Periódicos. diarios. revistas. libros y artícu...,5.0,4.7,4.5,4.9,5.5,3.8
26,Educación,5.5,2.9,1.1,0.8,2.1,1.7
27,Restaurantes y comidas fuera del hogar,7.4,6.6,7.4,6.4,8.5,7.3
28,Cuidado personal,5.9,5.4,4.5,6.9,5.7,5.1

2) **Cree una base de datos SQL y almacene el DataFrame final obtenido en el punto anterior como tabla**

In [ ]:
#se crea la base de datos SQL
import sqlite3 as sql

In [ ]:
#se crea el enlace a la base de datos
enlace = sql.connect("IPC.db")

In [ ]:
import pandas.io.sql as pd_sql

#se almacena el DataFrame como tabla en la base creada
pd_sql.to_sql(df4,'IPC',enlace, index=False)

#se crea la base de datos IPC
# enlace es la conexión a la base IPC, index=False para no almacenar el índice de Python

29

3) **Realice al menos dos queries con SQL a través de Python sobre la tabla almacenada y muestre el resultado en formato DataFrame.**

In [ ]:
#ejecución de querie (lectura de la tabla completa)
query='select * from IPC'

In [ ]:
#creacion de un dataframe en Pandas a partir de la consulta
df_sql1 = pd.read_sql_query(query, enlace)

In [ ]:
df_sql1

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,6.7,5.5,4.7,3.9,5.6,4.6
1,Carnes y derivados,3.0,2.8,3.0,1.9,1.3,1.5
2,Leche. productos lácteos y huevos,4.4,5.2,3.3,3.7,5.5,4.7
3,Aceites. grasas y manteca,3.3,3.4,2.3,2.5,3.0,3.8
4,Frutas,10.0,11.8,9.5,10.1,11.9,10.8
5,Verduras. tubérculos y legumbres,8.9,3.7,1.9,1.8,-7.1,-0.8
6,Azúcar. dulces. chocolate. golosinas. etc.,4.0,4.3,2.9,4.2,4.3,4.0
7,Café. té. yerba y cacao,3.4,3.3,2.5,3.9,5.8,3.1
8,Aguas minerales. bebidas gaseosas y jugos,9.3,6.8,4.9,5.3,6.5,6.2
9,Bebidas alcohólicas,7.1,8.4,7.3,8.4,10.0,7.8
10,Tabaco,6.4,6.5,6.4,6.5,6.8,6.4
11,Prendas de vestir y materiales,3.7,3.4,4.5,4.3,5.0,4.4
12,Calzado,5.2,5.1,4.5,4.2,2.6,3.8
13,Alquiler de la vivienda y gastos conexos,4.9,5.2,1.7,2.6,2.4,0.3
14,Alquiler de la vivienda,4.7,5.2,1.4,2.3,2.3,0.1
15,Electricidad. gas y otros combustibles,2.1,3.9,4.1,3.3,4.7,8.1
16,Bienes y servicios para la conservación del hogar,5.8,5.8,6.2,6.8,6.1,5.3
17,Productos medicinales. artefactos y equipos pa...,5.4,5.6,5.2,6.1,5.4,6.0
18,Gastos de prepagas,6.9,8.6,8.3,4.5,6.8,7.0
19,Adquisición de vehículos,6.2,4.2,4.9,5.4,4.3,3.7
20,Funcionamiento de equipos de transporte personal,3.9,7.1,7.0,6.9,8.1,6.8
21,Combustibles y lubricantes para vehículos de u...,4.2,7.2,7.5,7.2,8.0,5.9
22,Transporte público,5.7,8.5,7.9,5.6,18.6,5.8
23,Servicios de telefonía e internet,2.7,3.5,3.5,5.9,6.2,3.6
24,Servicios recreativos y culturales,6.2,8.0,13.5,5.3,3.0,7.9
25,Periódicos. diarios. revistas. libros y artícu...,5.0,4.7,4.5,4.9,5.5,3.8
26,Educación,5.5,2.9,1.1,0.8,2.1,1.7
27,Restaurantes y comidas fuera del hogar,7.4,6.6,7.4,6.4,8.5,7.3
28,Cuidado personal,5.9,5.4,4.5,6.9,5.7,5.1

In [ ]:
#segunda consulta obtener dataframe con los promedios de GBA,Pampeana y Noroeste
query2 = "SELECT AVG(GBA), AVG(Pampeana), AVG(Noreste) FROM IPC"

In [ ]:
df_sql2 = pd.read_sql_query(query2, enlace)

In [ ]:
df_sql2

   AVG(GBA)  AVG(Pampeana)  AVG(Noreste)
0  5.444828       5.606897      5.048276

In [ ]:
#Tercera: se crea un dataframe con la consulta de todos los registros donde Pampeana es mayor que 6
#se arma la consulta
query3= "SELECT * FROM IPC WHERE Pampeana > 6.0"

In [ ]:
#se carga el dataframe
df_sql3 = pd.read_sql_query(query3, enlace)

In [ ]:
df_sql3

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Frutas,10.0,11.8,9.5,10.1,11.9,10.8
1,Aguas minerales. bebidas gaseosas y jugos,9.3,6.8,4.9,5.3,6.5,6.2
2,Bebidas alcohólicas,7.1,8.4,7.3,8.4,10.0,7.8
3,Tabaco,6.4,6.5,6.4,6.5,6.8,6.4
4,Gastos de prepagas,6.9,8.6,8.3,4.5,6.8,7.0
5,Funcionamiento de equipos de transporte personal,3.9,7.1,7.0,6.9,8.1,6.8
6,Combustibles y lubricantes para vehículos de u...,4.2,7.2,7.5,7.2,8.0,5.9
7,Transporte público,5.7,8.5,7.9,5.6,18.6,5.8
8,Servicios recreativos y culturales,6.2,8.0,13.5,5.3,3.0,7.9
9,Restaurantes y comidas fuera del hogar,7.4,6.6,7.4,6.4,8.5,7.3

In [ ]:
#Agregar un nuevo registro

# Crear un cursor
cursor = enlace.cursor()

# Definir los valores para el nuevo registro
Producto='Productos de limpieza'
GBA=	3.1
Pampeana=2.7
Noreste=2.5
Noroeste=3.25
Cuyo=4.67
Patagonia=5.5

# Ejecutar la consulta INSERT para agregar el nuevo registro
cursor.execute('INSERT INTO IPC (Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia) VALUES (?, ?, ?,?,?,?,?)', (Producto,GBA, Pampeana, Noreste,Noroeste,Cuyo,Patagonia))

# Guardar los cambios en la base de datos
enlace.commit()

#cerramos el cursor
cursor.close()

In [ ]:
#leemos la tabla actualizada y la guardamos en un dataframe
df_sql4=pd.read_sql_query(query, enlace)

In [ ]:
df_sql4

,Producto,GBA,Pampeana,Noreste,Noroeste,Cuyo,Patagonia
0,Pan y cereales,6.7,5.5,4.7,3.90,5.60,4.6
1,Carnes y derivados,3.0,2.8,3.0,1.90,1.30,1.5
2,Leche. productos lácteos y huevos,4.4,5.2,3.3,3.70,5.50,4.7
3,Aceites. grasas y manteca,3.3,3.4,2.3,2.50,3.00,3.8
4,Frutas,10.0,11.8,9.5,10.10,11.90,10.8
5,Verduras. tubérculos y legumbres,8.9,3.7,1.9,1.80,-7.10,-0.8
6,Azúcar. dulces. chocolate. golosinas. etc.,4.0,4.3,2.9,4.20,4.30,4.0
7,Café. té. yerba y cacao,3.4,3.3,2.5,3.90,5.80,3.1
8,Aguas minerales. bebidas gaseosas y jugos,9.3,6.8,4.9,5.30,6.50,6.2
9,Bebidas alcohólicas,7.1,8.4,7.3,8.40,10.00,7.8
10,Tabaco,6.4,6.5,6.4,6.50,6.80,6.4
11,Prendas de vestir y materiales,3.7,3.4,4.5,4.30,5.00,4.4
12,Calzado,5.2,5.1,4.5,4.20,2.60,3.8
13,Alquiler de la vivienda y gastos conexos,4.9,5.2,1.7,2.60,2.40,0.3
14,Alquiler de la vivienda,4.7,5.2,1.4,2.30,2.30,0.1
15,Electricidad. gas y otros combustibles,2.1,3.9,4.1,3.30,4.70,8.1
16,Bienes y servicios para la conservación del hogar,5.8,5.8,6.2,6.80,6.10,5.3
17,Productos medicinales. artefactos y equipos pa...,5.4,5.6,5.2,6.10,5.40,6.0
18,Gastos de prepagas,6.9,8.6,8.3,4.50,6.80,7.0
19,Adquisición de vehículos,6.2,4.2,4.9,5.40,4.30,3.7
20,Funcionamiento de equipos de transporte personal,3.9,7.1,7.0,6.90,8.10,6.8
21,Combustibles y lubricantes para vehículos de u...,4.2,7.2,7.5,7.20,8.00,5.9
22,Transporte público,5.7,8.5,7.9,5.60,18.60,5.8
23,Servicios de telefonía e internet,2.7,3.5,3.5,5.90,6.20,3.6
24,Servicios recreativos y culturales,6.2,8.0,13.5,5.30,3.00,7.9
25,Periódicos. diarios. revistas. libros y artícu...,5.0,4.7,4.5,4.90,5.50,3.8
26,Educación,5.5,2.9,1.1,0.80,2.10,1.7
27,Restaurantes y comidas fuera del hogar,7.4,6.6,7.4,6.40,8.50,7.3
28,Cuidado personal,5.9,5.4,4.5,6.90,5.70,5.1
29,Productos de limpieza,3.1,2.7,2.5,3.25,4.67,5.5

In [ ]:
# Cerrar la conexión a la base de datos
enlace.close()